### ISSUE TITLE
login page, Username validation should be case insensitive.

### ISSUE THREAD

**Issue by aalap03** [cparmar1274/reviewanalyticsv1#29]

**Comment by cparmar1274** [comment]
Enabled username case insensitivity.
Link :  http://justreviewz.herokuapp.com/login
use case 1:
username :  pai-northern-thai-kitchen-toronto-5
password : h{vcqaONNfQY6UaBN21}

use case 2:
username :  pai-northern-thAI-kitchen-toronto-5 or any variation
password : h{vcqaONNfQY6UaBN21}
